# Generated by Django 4.0.4 on 2022-04-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualEnterpriseSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('industry_code_ANZSIC', models.CharField(max_length=200)),
                ('industry_name_ANZSIC', models.CharField(max_length=200)),
                ('rme_size_grp', models.CharField(max_length=200)),
                ('variable', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=200)),
            ],
        ),
    ]
